name: Run Greet Action

on:
  push:
    branches:
      - master

jobs:
  greet-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run custom greet action
        uses: ./java-actions
        with:
          name: "Raju"
